README.md

This replaces the README template with project overview and getting started content.

Add a bit of overview to the readme for newcomers

---

.appveyor.yml
.github/workflows/docbuild.yml
.github/workflows/test_crippledfs.yml
README.md
requirements-devel.txt

Kind of pedantic, but also reduces the opportunity for missed steps.

MNT: Reduce installation steps by 1

---

docs/source/index.rst

Closing #43, this initial description is adapted from OHBM brainhack 2022 project pitch.

replaced the generic "datalad extension" content with some general overview of the project

---

datalad_dataverse/remote.py

This PR adds the basic functionality for 'checkpresent' and 'transfer_store'.

Add basic functionality for checkpresent and transfer_store

---

datalad_dataverse/remote.py

Added remove function

---

datalad_dataverse/create_sibling_dataverse.py

Fleshing out create-sibling a bit more

---

datalad_dataverse/remote.py
datalad_dataverse/tests/test_remote.py
datalad_dataverse/tests/utils.py
datalad_dataverse/utils.py

Smoke test for the remote implementation

---

datalad_dataverse/utils.py

```python
from datalad_dataverse.utils import DATASET_SUBJECTS
```

Provide list of valid dataset subjects

---

datalad_dataverse/create_sibling_dataverse.py

should fix #80 at least for now; improvements welcome :)

DOC: add a slightly more appropriate docstring for the credential

---

datalad_dataverse/create_sibling_dataverse.py

Add docstream to create_sibling_dataverse

---

docs/source/cmdline.rst
docs/source/index.rst
docs/source/modref.rst

DOC: structure Python and CMD overview prettier

---

docs/source/index.rst
docs/source/settingup.rst

To not cause confusion when they follow installation instructions or can't find a tutorial

Add a few alpha stage/pre-release markers to the docs

---

datalad_dataverse/create_sibling_dataverse.py
datalad_dataverse/tests/test_create_sibling_dataverse.py

Something like this is done now:
```
No collection 'coke' found, existing ones (and IDs) are: Eleni Castro Da… (3), HCPDS Dataverse (7)
```
Right now the numerical IDs are not useful, but they will be when
datalad/datalad-dataverse#137 is addressed.
Closes: datalad/datalad-dataverse#138

When an unknown collection is given, error with advice

---

datalad_dataverse/tests/test_create_sibling_dataverse.py
datalad_dataverse/tests/test_remote.py

- Merge duplicate implementations
- Standardize collection names
- Disable test broken by #143
Closed #141

Test consolidation

---

requirements-devel.txt
requirements.txt
setup.cfg

All required code made it into respective releases.

Depend on released versions again

---

datalad_dataverse/remote.py
datalad_dataverse/utils.py

Start reorganizing special remote implementation

---

datalad_dataverse/baseremote.py
datalad_dataverse/remote.py

The docs are still largely duplicates. The fate will be determined when a decision is made on whether to keep export mode supported or not.
Closes #177 
Closes #183

Split export from non-export remote aspects

---

datalad_dataverse/baseremote.py
datalad_dataverse/dataset.py
datalad_dataverse/tests/test_remote.py

Improve layout and efficiency in non-export mode

---

datalad_dataverse/dataset.py
datalad_dataverse/tests/test_dataset.py

Modeled after the test_pydataverse ones.
Closes #236

Some dedicated tests for OnlineDataverseDataset, fix `rename_file()`

---

datalad_dataverse/add_sibling_dataverse.py

`add_sibling_dataverse` performs no such handling anymore, and nothing elses used them.
Closes #186

Drop obsolete metadata-handling methods

---

datalad_dataverse/utils.py

Fixes #171 and fixes #253. A review from @mih would be appreciated.

Use credman.obtain() to search existing & prompt for new creds in one go

---

datalad_dataverse/add_sibling_dataverse.py

I'm not too familiar with the constraints the parameters have to comply to, so I mirrored what the old-style constraints ensured, and added constraints where I ran into failures in trial-and-error attempts (e.g., a required scheme component for the URL). I'm sure I missed some things, though, so if anyone knows about additional constraint details, feel free to push into this branch.
Fixes #102

Add basic parameter validation from datalad-next

---

datalad_dataverse/dataset.py

Update and decomplexify `OnlineDataverseDataset`

---

datalad_dataverse/add_sibling_dataverse.py
datalad_dataverse/tests/test_add_sibling_dataverse.py

Also gives it another general implementation update.

Remove recursive-mode from `add_sibling_dataverse`

---

.readthedocs.yml

An attempt to fix or troubleshoot #268

configure readthedocs to use Python 3.10 instead of 3.7

---

docs/source/faq.rst
docs/source/index.rst

A first draft of a  "why do my files look so weird" explanation

Add a "why do my files look so weird"-explanation

---

datalad_dataverse/add_sibling_dataverse.py

Adjust add-sibling docstring

---

CHANGELOG.md
datalad_dataverse/add_sibling_dataverse.py
requirements-devel.txt
setup.cfg

Depend on the 1.0.0b2 release of datalad-next

---

datalad_dataverse/tests/utils.py

The changelog suggested minimal changes, but the format seems to be substantially different now (see diff). The changes also break pyDataverse's internal data model and validation.
This changeset bypasses all that.
No production code should be affected, we already discontinued the dataverse dataset creation, due to difficulties knowing what an instance will require. This helps us now, and we only have to track demo.dataverse.org, rather than being forced to perform version-based metadata reformating and relabeling.

Dataverse v5.13 seems to have broken pyDataverse metadata handling

---

README.md

doc-link lead to 404, this fixes it.
closes #295

Update Links to Docs

---

datalad_dataverse/tests/test_pydataverse.py
datalad_dataverse/tests/utils.py
docs/source/conf.py

Ensure use of latest required metadata when creating a dataset on demo.dataverse.org

---

docs/source/settingup.rst

- Closes #304
- Closes #302
Do you think that's good enough, @pdurbin, @yarikoptic ?

DOC: Mention extension loading in setup page

---

datalad_dataverse/dataset.py

Closes #310.
As mentioned in #310, I am not sure if this is a good solution and am looking forward to your ideas on this one, hence I'll mark it as a draft for now.

Use non-persistentId mode for data file retrieval

---

datalad_dataverse/tests/test_add_sibling_dataverse.py

explorations are in #320, specifically https://github.com/datalad/datalad-dataverse/issues/320#issuecomment-2245172789. I didn't find where/when this message chance was introduced, and I'm not making it too easy for myself with this "fix".

Test: Adjust assertion for new message

---

.appveyor.yml

see https://github.com/datalad/datalad-next/issues/756 and https://github.com/datalad/datalad/pull/7649 for background

ci: switch to codecov cli on macos
