datalad/datalad-dataverse

.appveyor.yml
README.md
tools/ci/dladmin.json
tools/ci/init_dataverse.sh
tools/ci/root-dv.json
tools/ci/setup_docker_dataverse.sh
tools/ci/user1.json

Closes #2
This sets up a dataverse docker instance in the Ubuntu AppVeyor build. It's NOT provided on macOS and Windows. However, I think this should suffice, since the project isn't about running dataverse - the server system doesn't really matter for us.
Currently, this is not yet set up to use HTTPS, but only HTTP. Again, I don't think it's crucial to get going, but would be a nice-to-have.

Provide basic docker setup on appveyor

---

.appveyor.yml
.github/workflows/docbuild.yml
.github/workflows/test_crippledfs.yml
CONTRIBUTORS
datalad_dataverse/__init__.py
datalad_dataverse/conftest.py
datalad_dataverse/tests/test_register.py
requirements-devel.txt
requirements.txt
setup.cfg
tools/ci/setup_docker_dataverse.sh

For now we need to depend on datalad-next
as well as datalad from the future.
The former for credentials, the latter for
proper pytest support. This will change when
datalad 0.17 is released (and a subsequent
datalad-next release).
Otherwise we need pydataverse for now.
Closes #29

Setup requirements

---

datalad_dataverse/remote.py

This PR implements a basic version of the initremote method. It forces the user to provide the URL to the dataverse instance and the doi to the dataset and checks whether the instance and dataset exist.

add basic implementation of initremote

---

.appveyor.yml
.github/workflows/test_crippledfs.yml
tools/ci/setup_docker_dataverse.sh

Unauthenticated pulls from the same IP are limited; you get double the amount when authenticating with a  free account. This PR adds the necessary log in to the CI

Add dockerhub login to CI for more container pulls

---

datalad_dataverse/remote.py
datalad_dataverse/tests/test_utils.py
datalad_dataverse/utils.py

add checks for doi and url config parameters 
remove trainging slash in url
reformat doi string when necessary
lazy evaluting of annex config

improve doi and url handling

---

docs/source/glossary.rst
docs/source/index.rst

Here is just the start of a table to compare the terms.

DOC: add glossary page to define how Dataverse and DataLad terms relate

---

datalad_dataverse/create_sibling_dataverse.py

This makes the `--metadata` option to `create-sibling-dataverse`
optional and introduces dedicated functions to provide every required
aspect of a dataverse dataset's metadata.

Make --metadata optional

---

docs/source/glossary.rst

Sadly the table structure doesn't format nicely (i adds a scrollbar instead of linebreaks), so I reformatted it to a glossary. I also added some basic descriptions

DOC: reformat glossary and add basic descriptions

---

datalad_dataverse/__init__.py
datalad_dataverse/tests/test_remote.py

This is implemented via a custom URL mapping config
```
datalad.clone.url-substitute.dataverse=(',^(http[s]*://.*)/dataset.xhtml\\?persistentId=(doi:[^&]+)(.*)$,datalad-annex::?type=external&externaltype=dataverse&url=\\1&doi=\\2&encryption=none',)
```
for this to work, users have to configure the dataverse extension for
auto-loading, but setting the `datalad.extensions.load=dataverse`
config switch in the `global` scope.
For now, this convenience expects a dataset deposit in non-export mode.
But we might want to revisit that later.
Closes #87

Support datalad-clone directly from dataset landing page

---

datalad_dataverse/remote.py
datalad_dataverse/tests/test_remote.py
requirements.txt

There is not longer a need to pre-deploy a token via an env-var. The
special remote will no query for one automatically and also
store it in a local credential store on successful use. Subsequent
usage no longer requires a re-specification, because the credential
is rediscovered via a "realm" property.

Hook into the datalad-next credential system

---

.appveyor.yml
.github/workflows/test_crippledfs.yml
CONTRIBUTING.md
datalad_dataverse/tests/__init__.py
datalad_dataverse/tests/test_create_sibling_dataverse.py
datalad_dataverse/tests/test_remote.py
datalad_dataverse/tests/utils.py
tools/ci/setup_docker_dataverse.sh

The change makes it possible to run all tests against this common
instance, after specifying a token. The standard user account token
handed out to any user of this instance is a sufficiently capable
admin token.
When no particular dataverse instance URL is specified, all tests
are performed against demo.dataverse.org. This substantially lowers
the barrier for running tests, at the cost of a much slower test
execution.
When no admin token for the tests is given, a prominent warning
with instructions is now given, rather than merely skipping most tests.
The environment variable scheme for configurating the test setup has
been standardized to the following setup:
- DATAVERSE_TEST_URL: Dataverse instance base URL, defaults to
https://demo.dataverse.org
- DATAVERSE_TEST_BASECOLLECTION: …

Enable test execution against demo.dataverse.org

---

.appveyor.yml

Right now the new setup yields 10.20220624 for all platforms.

Use more recent git-annex for appveyor tests

---

.appveyor.yml

It makes sense to have this run, because other platforms are tested like
this too, and the docker setup is expensive and fragile (ie., does not
yield a working deployment each time).
Closes #129

Add linux CI run without docker dataverse

---

CONTRIBUTING.md

I cut excessive detail (with a good chance to become outdated over time)
and reference the contributing guidelines of the core package.
I also cut the ultra-detailed naming scheme for branches and commit
subjects, which are not even observed in the core package.
Closes datalad/datalad-dataverse#116

De-duplicate contributing info, and simplify

---

datalad_dataverse/create_sibling_dataverse.py
datalad_dataverse/remote.py
datalad_dataverse/tests/test_create_sibling_dataverse.py
datalad_dataverse/utils.py

Previously, two different implementations were used for the special
remote and for the `create-sibling-dataverse` command.
This change consolidates both implementation on a single, improved one:
`datalad_dataverse.utils.get_api()`. This implies the following changes:
- `create-sibling-dataverse` now stores entered credentials, after
they were tested. Closes datalad/datalad-dataverse#115
Closes datalad/datalad-dataverse#113
- Credential lookup failure and authentication failure are now
communicated as two different, documented exceptions.
- Test implementations for `create-sibling-dataverse` have been
simplified, no custom environment patching is needed due to
proper credential store usage.
- `create-sibling-dataverse` implementation was simplified, because
no credentials need to be passed …

De-duplicate, homogenize, and fix API authentication

---

.github/workflows/test_crippledfs.yml

In response to https://github.com/datalad/datalad-dataverse/pull/147#issuecomment-1214849391

CI: Turn dockerhub login from separate job into step within existing job

---

datalad_dataverse/create_sibling_dataverse.py

Similar to how other create-sibling-* commands provide sibling name defaults,
create-sibling-dataverse now calls git-part siblings 'dataverse' by default
unless instructed otherwise. Fixes #140
This will need at least a smoke test, but since the create-sibling-dataverse tests are currently disabled I didn't add one yet.

BF: Provide sibling name default

---

datalad_dataverse/create_sibling_dataverse.py

There is no need for any of its functionality, and it also broke API with the 0.18.0 DataLad release.
Closes #159
Closes #160

Use `json` directly instead of DataLad's `json_py`

---

datalad_dataverse/remote.py

It simply confused me.
Closes #169

Convert `namedtuple` declaration to more boring syntax

---

datalad_dataverse/remote.py

As speculated in #180 there should be no need for any special casing. Hence I tried to just rip all respective conditionals out.
Locally that makes no difference re the associated `datalad_annex` test.
Possibly this means that special casing only had an impact on the operations in export mode (which seems to be untested).
Closes #180
Closes #190

Bluntly rip out DATALAD_ANNEX_SPECIAL_KEYS handling

---

datalad_dataverse/remote.py

`self.remove_from_filelist(re)`, where `re` is the Python regex module.
It is now passing `replace_id`, which is checked for `not None` directly before. However, this is a blind fix. Clearly this part of the code is not tested enough to be able to tell whether this is actually a fix.
Closes #195

Replace non-sensical call

---

datalad_dataverse/conftest.py
datalad_dataverse/tests/fixtures.py
datalad_dataverse/tests/test_pydataverse.py

This adds 
- a test to document the behavior of file removal from a dataverse dataset 
- a new fixture providing a dataset in a published collection.

test file removal

---

datalad_dataverse/conftest.py
datalad_dataverse/tests/fixtures.py
datalad_dataverse/tests/test_create_sibling_dataverse.py
datalad_dataverse/tests/test_pydataverse.py

ATM we are no capable of cleaning up such datasets after a testrun, because we do not have superuser permissions on demo.dataverse.org
This also removed the now obsolete test fixtures.
Issue #216 tracks a suitable fix.
Closes #215

Remove test aspects requiring published datasets

---

datalad_dataverse/dataset.py
datalad_dataverse/remote.py

This allows for removing any direct dependency of the special remote implementations from `pyDataverse` (ping #200).
Closes #219

`OnlineDataverseDataset.rename_file()`

---

datalad_dataverse/tests/test_utils.py

This PR fixes a bug in directory-related tests in ``test_utils.py`` where string representations of paths were used and led to problems with os-specific path-dividers

compare Path-objects in tests

---

datalad_dataverse/remote.py
datalad_dataverse/tests/test_utils.py
datalad_dataverse/utils.py

Fixes issue #218 
This PR uses a separate simple encoding mechanism to replace a leading ``.`` in a name with a ``_.``. Consequently, it also replaces a leading ``_``  with a ``__`` to prevent name collisions between encoded names and existing names.
To keep the number of quotations low, the default escape character has been changed from ``_`` to ``-``.
Also, while it is not strictly necessary, we encode a leading dot in a filename as well. That unifies the decoding of names without the need to know whether the resulting name refers to a directory or a file.

Use simpler quotation for leading dots

---

datalad_dataverse/baseremote.py
datalad_dataverse/dataset.py
datalad_dataverse/remote.py
datalad_dataverse/tests/test_remote.py

The special remote implementations no longer need to worry about this. All API methods that accept paths take care of the mangling automatically and internally.
Closes #83

Consolidate all path mangling to `OnlineDataverseDataset`

---

datalad_dataverse/baseremote.py

Seemingly unrelated problems can cause removal to fail, such as invalid dataset metadata.
Closes #192

Propagate `__cause__` for removal error

---

datalad_dataverse/remote.py

Went through both special remotes double-checking #246.
All seems right, so simply removed the TODO from a comment.
Closes #246

Consistent fallback for file IDs

---

datalad_dataverse/baseremote.py
datalad_dataverse/dataset.py
datalad_dataverse/tests/test_dataset.py
datalad_dataverse/tests/test_utils.py
datalad_dataverse/utils.py

Closes #220
Closes #259 
Last TODOs
```
=========================== short test summary info ===========================
798FAILED ..\tests\test_utils.py::test_path_mangling_identity - AssertionError: assert WindowsPath('.x') == PurePosixPath('.x')
799 +  where WindowsPath('.x') = Path('.x')
800 +  and   PurePosixPath('.x') = unmangle_path(PurePosixPath('_.x'))
801 +    where PurePosixPath('_.x') = mangle_path('.x')
802FAILED ..\tests\test_utils.py::test_path_mangling_sub_dirs - AssertionError: assert PurePosixPath('.x/.x/.x') == WindowsPath('.x/.x/.x')
803 +  where PurePosixPath('.x/.x/.x') = unmangle_path(PurePosixPath('_.x/_.x/_.x'))
804============ 2 failed, 14 passed, 4 warnings in 845.08s (0:14:05) =============
805
```

Consistent use of PurePosixPath for the dataverse remote path

---

datalad_dataverse/utils.py

Fixes issue #262 
This PR fixes a faulty backslash representation in doc-strings

Fix backslash representation in doc-strings

---

datalad_dataverse/tests/test_utils.py
datalad_dataverse/utils.py

*Not sure this is helpful, but it would take care of Unicode file-name handling, if I am not mistaken. WDYT?*
This PR enables path mangling to encode all non-safe characters including Unicode-characters. This is a simple hex-number based encoding that servers two purposes:
- convert a given file name into a legal "dataverse" file name
- ensure that different given file names are mapped onto different dataverse files, i.e. no name collisions
Encoding become a little more bulky because codes have an escape character at the beginning and the end of the encoding.

Encode all non-safe file name characters including unicode-characters

---

docs/source/conf.py
docs/source/settingup.rst
requirements-devel.txt

Add description template snippet for copy-pasting

---

datalad_dataverse/dataset.py

The .ok is part of the [requests API](https://requests.readthedocs.io/en/latest/api/#requests.Response.ok), but not part of the httpx API. An equivalent check, according to the requests docs, is to use response.status_code < 400 (In fact, requests' implementation is a try/except around raise_for_status, but this should be the same, although we could use the same pattern instead.)
Note that response.status_code < 400 should work with both, requests and httpx, and thus remain backwards compatible.
Closes #308.

Replace `response.ok` with `response.status_code < 400`

---

.appveyor.yml

It is unclear why this is necessary. But we get a 401 response from `datalad-installer`.
The new approach uses what `datalad-next` is using to install on Windows.

ci(appveyor): update git-annex installation

---

datalad_dataverse/tests/test_pydataverse.py

Despite the patch-level version change there were breaking API changes.
This change adjusts the test helpers only, as a first step to address the API changes.
It is based on an analysis in
https://github.com/datalad/datalad-dataverse/issues/310

test(`pydataverse`): accomodate newer pyDataverse versions (0.3.2+)

---

datalad_dataverse/dataset.py

Alternative implementation to https://github.com/datalad/datalad-dataverse/pull/313 proposed in its description.

fix(`download_file`): accomodate newer pyDataverse versions (0.3.2+)

---

datalad_dataverse/dataset.py

Otherwise, the files will not have the correct hashes, as dataverse replaces, e.g., csv or R table files with its own tabular data format.
To reproduce the issue #307 before and after the fix, either use an account at demo.dataverse.org, or do the [docker setup](https://guides.dataverse.org/en/latest/container/running/demo.html).
I used pipx to install everything into a venv, but pip should do the trick as well – with pipx I was able to ensure git-annex would pick up the binaries easily without having to fiddle around with the PATH too much.
```bash
$ cd datalad-dataverse
$ pipx install datalad
$ pipx inject --include-apps --force datalad datalad-next
$ pipx inject --include-apps --force --editable datalad .
```
Next we do the git setup, a local and "remote" repository:
```bash
$ cd ..  # …
```

Always use the original file format when downloading files

---

datalad_dataverse/tests/test_pydataverse.py

The docker compose setup as used in pyDataverse uses a different storage backend than demo.dataverse.org, so the storageIdentifier reports a non-s3:// address.
This commit detects the two most common ways of specifying localhost (leaving out 127.1 and the like) to allow for `local://` storageIdentifiers.
Relates to #320.

Allow check_upload assets to use docker

---

datalad_dataverse/tests/test_remote.py

Since Dataverse version 5.0, "storeKey when already present" of git-annex testremote will fail, as Dataverse forbade replacing files with identical names and checksums:
https://guides.dataverse.org/en/latest/user/dataset-management.html#duplicate-files Because we can't exclude any test from the test suite, but wouldn't want to disable the entire test suite, this change - rather ugly-ly - expects the check to fail, and tests for the right amount of failures in the test suite.
Note that it should hopefully be okay to only adjust the tests for this altered behavior of the remote - a checkpresent prior to transfer operations should AFAIK prevent upload/replace attempts of identical files.
see #320 for explorations.

test: Adjust testremote for expected failure amount
